### ISSUE TITLE
Multiapi-engine unavailable in central repository

### ISSUE THREAD

**Issue by antoinedvd** [corunet/scs-multiapi-plugin#145]
Hi, we can't used version >= 4.x.x because multiapi-engine is not availaible in the maven repo central ?

https://mvnrepository.com/artifact/net.coru

When I look into the `pom.xml` since `4.x.x` the scs-multiapi-plugin-maven` need the dependency of `multiapi-engine`. 
So we can't use it. 

Do you think to deploy this library someday ?

Thank you for this plugin anyway !

**Comment by jemacineiras** [comment]
HI @antoinedvd,
That was an error in the packaging in version 4.1.1, but it should be fixed in 4.2.2 and beyond.
Can you specify which version is failing to you?

Cheers

**Comment by antoinedvd** [comment]
Hi @jemacineiras, thank you for your answer, but I tried to use all the 4.x.x versions, with no result...

When you look on the mvn repo there are no multiapi-engine artifact at all. All the 4.x.x versions can't worked well without this dependency in the central repo.

**Comment by ohubaut** [comment]
Hello @jemacineiras, 

I can confirm that we are facing the same issue with the dependency being not published on central.
Also, the latest version published on central is the 4.1.1, unless you have some other releases in the staging area that you have not promoted yet.

**Comment by jemacineiras** [comment]
Hi guys,
You just raised an interesting fact because we are actually in the version 4.2.3 in maven central
https://mvnrepository.com/artifact/net.coru/scs-multiapi-maven-plugin/4.2.3
as you can see. 
But curious thing is browsing the sonatype search engine only the 4.1.1 appears
https://central.sonatype.dev/artifact/net.coru/scs-multiapi-maven-plugin/4.1.1

We will investigate why that happend.

Cheers!!

**Comment by antoinedvd** [comment]
Hi @jemacineiras , like I said, for me the main problem is that the `multiapi-engine` is not available on the repo. The `scs-multiapi-maven-plugin` needs this dependency to be available on the repo. Without it we can't use the plugin. 
I think you just need to deploy this dependency on the repo to be work correctly.

**Comment by jemacineiras** [comment]
Hi @antoinedvd,
Let me explain, the engine will never be in maven central. We will never deploy the engine apart from the plugins, since is the common element for Maven and Gradle plugins, and that is.
What we do is create a far jar (shadow jar) for the plugins with all the required classes and dependencies, so you will never be worried about old versions or so. 
So now, what's it the real problem:
When we release the 4.1.1 we realize the building process was broken. So no fat jar is created and the error for the dependency appears. We release the 4.2.2 fixing this and other things, so the `multiapi-engine` requirement as no longer and error, neither a warning. 
So what is happening now, for some reason we don't know code is being accepted and deployed but looks is not pushed to all mirrors of maven central, since appears in some search engines and not in others (as you can see in my last post)
![Changed-version-to-publish-144-·-corunet-scs-multiapi-plugin-6eda9dc](https://user-images.githubusercontent.com/68995937/204853465-3c48726f-ce69-42e0-b6cb-e11ea3a31680.png)

There you can see the output of the action where the latest version at now (4.2.3) is being pushed and accepted by the system who manage maven central.
May be as @ohubaut said the latest releases are kept in the staging area. We are investigating about.
Please be patient.
Regards

**Comment by antoinedvd** [comment]
Hi @jemacineiras , thank you very much for your detail response, it's crystal clear now !
So I will be patient. ;)

Kind regars

**Comment by jemacineiras** [comment]
Hi @antoinedvd,

Looks like the problem was in the side of Maven Central Repository. After opened a ticket, they verified all versions were there, and trigger a reindex. It looks like the problem is solved. Do you mind try again to run a` mvn clean install ` with the latest version (4.2.3 nowadays)?

**Comment by antoinedvd** [comment]
Hello @jemacineiras,
Everything's fine now with the 4.2.3 ! 
`mvn clean install` works and the code was generated. 👍
Thank you for your help in my issue. 

Now we have a small problem (not blocking) with the library because we expected it to generate annotations for checking beans, just like the open api generator library does (@Valid, @Size, etc.). Do you know if this kind of evolution is planned in the project roadmap or not? 

I close this ticket, for me the initial issue is fixed. 

Regards

**Comment by jemacineiras** [comment]
Hi @antoinedvd,

¨Now we have a small problem (not blocking) with the library because we expected it to generate annotations for checking beans, just like the open api generator library does (@Valid, @SiZe, etc.). Do you know if this kind of evolution is planned in the project roadmap or not?¨

Is in the future, once we get an stable template for build. If you need that soon you can always open us an issue, so we will handle it asap.

For you to know, we are merging with a big company, so this repo will migrate, also de packaging and so. Business requirements. So probably we can see to make it happen in Q1.

Cheers
